import DummyAppliancesImage from "@/assets/images/dummy-applinces.png";

export const productsArr = [
  {
    id: 1,
    name: "Frigidaire",
    desp: "27 cu. ft. French Door Refrigerator...",
    avatar: DummyAppliancesImage,
    Inventory: 10,
    color: "Black",
    price: "49.90",
    Rating: "4.8",
    votes: "32",
  },
  {
    id: 2,
    name: "Frigidaire",
    desp: "27 cu. ft. French Door Refrigerator...",
    avatar: DummyAppliancesImage,
    Inventory: 30,
    color: "Black",
    price: "49.90",
    Rating: "4.8",
    votes: "32",
  },
  {
    id: 3,
    name: "Frigidaire",
    desp: "27 cu. ft. French Door Refrigerator...",
    avatar: DummyAppliancesImage,
    Inventory: 0,
    color: "Black",
    price: "49.90",
    Rating: "4.8",
    votes: "32",
  },
  {
    id: 4,
    name: "Frigidaire",
    desp: "27 cu. ft. French Door Refrigerator...",
    avatar: DummyAppliancesImage,
    Inventory: 40,
    color: "Black",
    price: "49.90",
    Rating: "4.8",
    votes: "32",
  },
  {
    id: 5,
    name: "Frigidaire",
    desp: "27 cu. ft. French Door Refrigerator...",
    avatar: DummyAppliancesImage,
    Inventory: 0,
    color: "Black",
    price: "49.90",
    Rating: "4.8",
    votes: "32",
  },
  {
    id: 6,
    name: "Frigidaire",
    desp: "27 cu. ft. French Door Refrigerator...",
    avatar: DummyAppliancesImage,
    Inventory: 56,
    color: "Black",
    price: "49.90",
    Rating: "4.8",
    votes: "32",
  },
  {
    id: 7,
    name: "Frigidaire",
    desp: "27 cu. ft. French Door Refrigerator...",
    avatar: DummyAppliancesImage,
    Inventory: 0,
    color: "Black",
    price: "49.90",
    Rating: "4.8",
    votes: "32",
  },
  {
    id: 8,
    name: "Frigidaire",
    desp: "27 cu. ft. French Door Refrigerator...",
    avatar: DummyAppliancesImage,
    Inventory: 32,
    color: "Black",
    price: "49.90",
    Rating: "4.8",
    votes: "32",
  },
  {
    id: 9,
    name: "Frigidaire",
    desp: "27 cu. ft. French Door Refrigerator...",
    avatar: DummyAppliancesImage,
    Inventory: 0,
    color: "Black",
    price: "49.90",
    Rating: "4.8",
    votes: "32",
  },
  {
    id: 10,
    name: "Frigidaire",
    desp: "27 cu. ft. French Door Refrigerator...",
    avatar: DummyAppliancesImage,
    Inventory: 0,
    color: "Black",
    price: "49.90",
    Rating: "4.8",
    votes: "32",
  },
  {
    id: 11,
    name: "Frigidaire",
    desp: "27 cu. ft. French Door Refrigerator...",
    avatar: DummyAppliancesImage,
    Inventory: 47,
    color: "Black",
    price: "49.90",
    Rating: "4.8",
    votes: "32",
  },
  {
    id: 12,
    name: "Frigidaire",
    desp: "27 cu. ft. French Door Refrigerator...",
    avatar: DummyAppliancesImage,
    Inventory: 0,
    color: "Black",
    price: "49.90",
    Rating: "4.8",
    votes: "32",
  },
  {
    id: 13,
    name: "Frigidaire",
    desp: "27 cu. ft. French Door Refrigerator...",
    avatar: DummyAppliancesImage,
    Inventory: 0,
    color: "Black",
    price: "49.90",
    Rating: "4.8",
    votes: "32",
  },
  {
    id: 14,
    name: "Frigidaire",
    desp: "27 cu. ft. French Door Refrigerator...",
    avatar: DummyAppliancesImage,
    Inventory: 0,
    color: "Black",
    price: "49.90",
    Rating: "4.8",
    votes: "32",
  },
  {
    id: 15,
    name: "Frigidaire",
    desp: "27 cu. ft. French Door Refrigerator...",
    avatar: DummyAppliancesImage,
    Inventory: 0,
    color: "Black",
    price: "49.90",
    Rating: "4.8",
    votes: "32",
  },
  {
    id: 16,
    name: "Frigidaire",
    desp: "27 cu. ft. French Door Refrigerator...",
    avatar: DummyAppliancesImage,
    Inventory: 0,
    color: "Black",
    price: "49.90",
    Rating: "4.8",
    votes: "32",
  },
  {
    id: 17,
    name: "Frigidaire",
    desp: "27 cu. ft. French Door Refrigerator...",
    avatar: DummyAppliancesImage,
    Inventory: 0,
    color: "Black",
    price: "49.90",
    Rating: "4.8",
    votes: "32",
  },
  {
    id: 18,
    name: "Frigidaire",
    desp: "27 cu. ft. French Door Refrigerator...",
    avatar: DummyAppliancesImage,
    Inventory: 0,
    color: "Black",
    price: "49.90",
    Rating: "4.8",
    votes: "32",
  },
  {
    id: 19,
    name: "Frigidaire",
    desp: "27 cu. ft. French Door Refrigerator...",
    avatar: DummyAppliancesImage,
    Inventory: 0,
    color: "Black",
    price: "49.90",
    Rating: "4.8",
    votes: "32",
  },
  {
    id: 20,
    name: "Frigidaire",
    desp: "27 cu. ft. French Door Refrigerator...",
    avatar: DummyAppliancesImage,
    Inventory: 0,
    color: "Black",
    price: "49.90",
    Rating: "4.8",
    votes: "32",
  },
];

export const ordersArr = [
  {
    id: 1,
    orderId: "#12512B",
    date: "May 5, 4:20 PM",
    customer: "Tom Anderson",
    paymentStatus: "paid",
    orderStatus: "Ready",
    total: "49.90",
  },
  {
    id: 2,
    orderId: "#12523C",
    date: "May 5, 4:15 PM",
    customer: "Jayden Walker",
    paymentStatus: "paid",
    orderStatus: "Ready",
    total: "34.36",
  },
  {
    id: 3,
    orderId: "#51232A",
    date: "May 5, 4:15 PM",
    customer: "Inez Kim",
    paymentStatus: "paid",
    orderStatus: "Ready",
    total: "3.36",
  },
  {
    id: 4,
    orderId: "#23534D",
    date: "May 5, 4:12 PM",
    customer: "Francisco Henry",
    paymentStatus: "paid",
    orderStatus: "Shipped",
    total: "29.74",
  },
  {
    id: 5,
    orderId: "#51323C",
    date: "May 5, 4:12 PM",
    customer: "Violet Phillips",
    paymentStatus: "paid",
    orderStatus: "Shipped",
    total: "23.74",
  },
  {
    id: 6,
    orderId: "#35622A",
    date: "May 5, 4:12 PM",
    customer: "Rosetta Becker",
    paymentStatus: "paid",
    orderStatus: "Shipped",
    total: "20.74",
  },
  {
    id: 6,
    orderId: "#34232D",
    date: "May 5, 4:12 PM",
    customer: "Dean Love",
    paymentStatus: "paid",
    orderStatus: "Ready",
    total: "20.74",
  },
  {
    id: 7,
    orderId: "#56212D",
    date: "May 5, 4:12 PM",
    customer: "Nettie Tyler",
    paymentStatus: "paid",
    orderStatus: "Ready",
    total: "20.74",
  },
  {
    id: 8,
    orderId: "#56212D",
    date: "May 5, 4:12 PM",
    customer: "Lora Weaver",
    paymentStatus: "pending",
    orderStatus: "Ready",
    total: "20.74",
  },
  {
    id: 8,
    orderId: "#12512B",
    date: "May 5, 4:12 PM",
    customer: "Vincent Cannon",
    paymentStatus: "pending",
    orderStatus: "Ready",
    total: "20.74",
  },
];

export const coupansArr = [
  {
    id: 1,
    coupondes: "Summer discount 10% off",
    couponName: "Summer2020",
    usage: "15 times",
    status: "Active",
    date: "May 5, 2020 - May 15, 2020",
  },
  {
    id: 2,
    coupondes: "Free shipping on all items",
    couponName: "Shipfreetomee15",
    usage: "42 times",
    status: "Active",
    date: "May 5, 2020 - May 15, 2020",
  },
  {
    id: 3,
    coupondes: "Discount for washing machines 5%",
    couponName: "Washingmachine5",
    usage: "12 times",
    status: "Active",
    date: "April 12, 2020 - April 20, 2020",
  },
  {
    id: 4,
    coupondes: "Summer discount 10% off",
    couponName: "Summer2020",
    usage: "8 times",
    status: "Active",
    date: "April 12, 2020 - April 20, 2020",
  },
  {
    id: 5,
    coupondes: "Free shipping on all items",
    couponName: "Shipfreetomee15",
    usage: "18 times",
    status: "Active",
    date: "April 12, 2020 - April 20, 2020",
  },
  {
    id: 6,
    coupondes: "Discount for washing machines 10%",
    couponName: "Washingmachine5",
    usage: "57 times",
    status: "Active",
    date: "Feb 14, 2020 - Feb 20, 2020",
  },
  {
    id: 7,
    coupondes: "Summer discount 15% off",
    couponName: "Summer2020",
    usage: "16 times",
    status: "Active",
    date: "Feb 14, 2020 - Feb 20, 2020",
  },
  {
    id: 8,
    coupondes: "Discount for washing machines 5%",
    couponName: "Washingmachine5",
    usage: "12 times",
    status: "Expired",
    date: "April 12, 2020 - April 20, 2020",
  },
  {
    id: 9,
    coupondes: "Summer discount 10% off",
    couponName: "Summer2020",
    usage: "8 times",
    status: "Expired",
    date: "April 12, 2020 - April 20, 2020",
  },
  {
    id: 10,
    coupondes: "Free shipping on all items",
    couponName: "Shipfreetomee15",
    usage: "18 times",
    status: "Expired",
    date: "April 12, 2020 - April 20, 2020",
  },
];

export const customersArr = [
  {
    id: 1,
    name: "Rakesh Mishra",
    location: "Sawaynchester",
    orders: "5",
    spent: "96.14",
  },
  {
    id: 2,
    name: "Lakshman singh",
    location: "Kaydenville",
    orders: "12",
    spent: "22.18",
  },
  {
    id: 3,
    name: "Dinanath sah",
    location: "East Freidaton",
    orders: "6",
    spent: "59.16",
  },
  {
    id: 4,
    name: "Anmol yadav",
    location: "South Marcellus",
    orders: "3",
    spent: "54.16",
  },
  {
    id: 5,
    name: "Raushan singh Rajput",
    location: "South Olestad",
    orders: "15",
    spent: "45.1",
  },
  {
    id: 6,
    name: "Lokesh Rahul",
    location: "Dereckberg",
    orders: "12",
    spent: "85.78",
  },
  {
    id: 7,
    name: "Randhir Kumar",
    location: "Franeckiview",
    orders: "5",
    spent: "128.66",
  },
  {
    id: 8,
    name: "Khushi Kumari",
    location: "Port Kathryne",
    orders: "7",
    spent: "113.39",
  },
  {
    id: 9,
    name: "Pooja Kumari",
    location: "McGlynntown",
    orders: "14",
    spent: "80.80",
  },
  {
    id: 10,
    name: "Ruhi Kumari",
    location: "Krystalview",
    orders: "5",
    spent: "42.03",
  },
];

export const customerOrderArr = [
  {
    id: 1,
    order: "#23534D",
    date: "May 25, 3:12 PM",
    status: "Pending",
    price: "$29.74",
  },
  {
    id: 2,
    order: "#12512B",
    date: "May 10, 2:00 PM",
    status: "Completed",
    price: "$23.06",
  },
  {
    id: 3,
    order: "#23534D",
    date: "April 18, 8:00 AM",
    status: "Completed",
    price: "$29.76",
  },
  {
    id: 4,
    order: "#76543E",
    date: "April 12, 8:00 AM",
    status: "Completed",
    price: "$23.06",
  },
  {
    id: 5,
    order: "#51323C",
    date: "April 10, 4:12 PM",
    status: "Completed",
    price: "$35.06",
  },
];

export const categories = [
  {
    id: 1,
    categories: "Refrigrators",
    count: "24 items",
    desp: "27 cu. ft. French Door Refrigerator...",
    avatar: DummyAppliancesImage,
    status: "Active",
  },
  {
    id: 2,
    categories: "Laundry",
    count: "24 items",
    desp: "27 cu. ft. French Door Refrigerator...",
    avatar: DummyAppliancesImage,
    status: "InActive",
  },
  {
    id: 3,
    categories: "Ranges",
    count: "24 items",
    desp: "27 cu. ft. French Door Refrigerator...",
    avatar: DummyAppliancesImage,
    status: "Active",
  },
  {
    id: 4,
    categories: "Cooktops",
    count: "24 items",
    desp: "27 cu. ft. French Door Refrigerator...",
    avatar: DummyAppliancesImage,
    status: "InActive",
  },
  {
    id: 5,
    categories: "Dishwashers",
    count: "24 items",
    status: "Active",
    desp: "27 cu. ft. French Door Refrigerator...",
    avatar: DummyAppliancesImage,
  },
];
export const subCategoriesArr = [
  {
    id: 1,
    categories: "French Door Refrigerators",
    count: "24 items",
    desp: "A stainless steel sentinel, the fridge hums faithfully, keeping your groceries crisp, chilled, and safe from spoilage.",
    avatar: DummyAppliancesImage,
  },
  {
    id: 2,
    categories: "Bottom Freezer Refrigerators",
    count: "24 items",
    desp: "A stainless steel sentinel, the fridge hums faithfully, keeping your groceries crisp, chilled, and safe from spoilage.",
    avatar: DummyAppliancesImage,
  },
  {
    id: 3,
    categories: "Side By Side Refrigerators",
    count: "24 items",
    desp: "A stainless steel sentinel, the fridge hums faithfully, keeping your groceries crisp, chilled, and safe from spoilage.",
    avatar: DummyAppliancesImage,
  },
  {
    id: 4,
    categories: "Top Freezer Refrigerators",
    count: "24 items",
    desp: "A stainless steel sentinel, the fridge hums faithfully, keeping your groceries crisp, chilled, and safe from spoilage.",
    avatar: DummyAppliancesImage,
  },
  {
    id: 5,
    categories: "Freezerless Refrigerators",
    count: "24 items",
    status: "Active",
    desp: "27 cu. ft. French Door Refrigerator...",
    avatar: DummyAppliancesImage,
  },
];

export const brandsArr = [
  {
    id: 1,
    name: "Bosch",
    desp: "24 items",
    avatar: DummyAppliancesImage,
    status: "active",
  },
  {
    id: 2,
    name: "Cafe",
    desp: "31 items",
    avatar: DummyAppliancesImage,
    status: "inactive",
  },
  {
    id: 3,
    name: "Frigidaire",
    desp: "12 items",
    avatar: DummyAppliancesImage,
    status: "active",
  },
];

export const unitsArr = [
  { label: "Not Applicable", value: "N/A" },
  { label: "Watt (W)", value: "W" },
  { label: "Kilowatt (kW)", value: "kW" },
  { label: "Voltage (V)", value: "V" },
  { label: "Ampere (A)", value: "A" },
  { label: "Liter (L)", value: "L" },
  { label: "Kilogram (kg)", value: "kg" },
  { label: "Gram (g)", value: "g" },
  { label: "Meter (m)", value: "m" },
  { label: "Centimeter (cm)", value: "cm" },
  { label: "Millimeter (mm)", value: "mm" },
  { label: "Inch (in)", value: "in" },
  { label: "Foot (ft)", value: "ft" },
  { label: "Degree Celsius (°C)", value: "°C" },
  { label: "Degree Fahrenheit (°F)", value: "°F" },
  { label: "Cubic Feet (cu ft)", value: "cu ft" },
  { label: "Cubic Meter (m³)", value: "m³" },
  { label: "Minute (min)", value: "min" },
  { label: "Hour (h)", value: "h" },
  { label: "Decibel (dB)", value: "dB" },
];

export const brandsTypeArr = [
  { label: "Major Appliance", value: "major" },
  { label: "Premium ", value: "premium" },
];

export const statesArr = [
  {
    label: "California",
    value: "CA",
  },
  {
    label: "Texas",
    value: "TX",
  },
  {
    label: "Florida",
    value: "FL",
  },
  {
    label: "New York",
    value: "NY",
  },
  {
    label: "Pennsylvania",
    value: "PA",
  },
  {
    label: "Illinois",
    value: "IL",
  },
  {
    label: "Ohio",
    value: "OH",
  },
  {
    label: "Georgia",
    value: "GA",
  },
  {
    label: "North Carolina",
    value: "NC",
  },
  {
    label: "Michigan",
    value: "MI",
  },
];

export const PHONE_VALIDATION = {
  pattern: {
    value: /^[0-9]{10}$/,
    message: "Contact number must be 10 digit"
  },
  required: "Contact number is required"
};

export const EMAIL_VALIDATION = {
  pattern: {
    value: /^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}$/,
    message: "Please enter a valid email address"
  },
  required: "Email is required"
};

